=== r2d2-ai/aiflow/internal/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "name",
        "type",
        "version",
        "description",
        "appModel",
        "triggers"
    ],
    "properties": {
        "actions": {
            "items": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "$ref": "#/definitions/action.Config"
            },
            "type": "array"
        },
        "appModel": {
            "type": "string"
        },
        "channels": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "connections": {
            "patternProperties": {
                ".*": {
                    "$schema": "http://json-schema.org/draft-07/schema#",
                    "$ref": "#/definitions/connection.Config"
                }
            },
            "type": "object"
        },
        "description": {
            "type": "string"
        },
        "imports": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "properties": {
            "items": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "$ref": "#/definitions/data.Attribute"
            },
            "type": "array"
        },
        "resources": {
            "items": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "$ref": "#/definitions/resource.Config"
            },
            "type": "array"
        },
        "schemas": {
            "patternProperties": {
                ".*": {
                    "$schema": "http://json-schema.org/draft-07/schema#",
                    "$ref": "#/definitions/schema.Def"
                }
            },
            "type": "object"
        },
        "triggers": {
            "items": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "$ref": "#/definitions/trigger.Config"
            },
            "type": "array"
        },
        "type": {
            "type": "string"
        },
        "version": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "type": "object",
    "definitions": {
        ".": {
            "required": [
                "name",
                "type",
                "version",
                "description",
                "appModel",
                "triggers"
            ],
            "properties": {
                "actions": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/action.Config"
                    },
                    "type": "array"
                },
                "appModel": {
                    "type": "string"
                },
                "channels": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "connections": {
                    "patternProperties": {
                        ".*": {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "$ref": "#/definitions/connection.Config"
                        }
                    },
                    "type": "object"
                },
                "description": {
                    "type": "string"
                },
                "imports": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/data.Attribute"
                    },
                    "type": "array"
                },
                "resources": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/resource.Config"
                    },
                    "type": "array"
                },
                "schemas": {
                    "patternProperties": {
                        ".*": {
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "$ref": "#/definitions/schema.Def"
                        }
                    },
                    "type": "object"
                },
                "triggers": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/trigger.Config"
                    },
                    "type": "array"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "action.Config": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "connection.Config": {
            "properties": {
                "ref": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "data.Attribute": {
            "additionalProperties": false,
            "type": "object"
        },
        "resource.Config": {
            "required": [
                "id",
                "data"
            ],
            "properties": {
                "data": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "schema.Def": {
            "required": [
                "type",
                "value"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "trigger.ActionConfig": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "if": {
                    "type": "string"
                },
                "input": {
                    "type": "object"
                },
                "output": {
                    "type": "object"
                },
                "ref": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "trigger.Config": {
            "required": [
                "id",
                "ref",
                "settings",
                "handlers"
            ],
            "properties": {
                "handlers": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/trigger.HandlerConfig"
                    },
                    "type": "array"
                },
                "id": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "trigger.HandlerConfig": {
            "required": [
                "settings",
                "actions"
            ],
            "properties": {
                "actions": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "$ref": "#/definitions/trigger.ActionConfig"
                    },
                    "type": "array"
                },
                "name": {
                    "type": "string"
                },
                "schemas": {
                    "$schema": "http://json-schema.org/draft-07/schema#",
                    "$ref": "#/definitions/trigger.SchemaConfig"
                },
                "settings": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
        "trigger.SchemaConfig": {
            "properties": {
                "output": {
                    "type": "object"
                },
                "reply": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "type": "object"
        }
    }
}

=== r2d2-ai/aiflow/core/examples/engine/aiflow.json
{
  "name": "_APP_NAME_",
  "type": "AIflow:app",
  "version": "0.0.1",
  "description": "My AIflow application description",
  "appModel": "1.0.0",
  "imports": [
    "github.com/r2d2-ai/ai-box/contrib/activity/log",
    "github.com/r2d2-ai/ai-box/contrib/trigger/rest",
    "github.com/r2d2-ai/ai-box/flow"
  ],
  "triggers": [
    {
      "id": "my_rest_trigger",
      "ref": "#rest",
      "settings": {
        "port": "8888"
      },
      "handlers": [
        {
          "settings": {
            "method": "GET",
            "path": "/test/:val"
          },
          "actions": [
            {
              "ref": "#flow",
              "settings": {
                "flowURI": "res://flow:simple_flow"
              },
              "input": {
                "in": "=$.pathParams.val"
              }
	    }
	  ]
        }
      ]
    }
  ],
  "resources": [
    {
      "id": "flow:simple_flow",
      "data": {
        "name": "simple_flow",
        "metadata": {
          "input": [
            { "name": "in", "type": "string",  "value": "test" }
          ],
          "output": [
            { "name": "out", "type": "string" }
          ]
        },
        "tasks": [
          {
            "id": "log",
            "name": "Log Message",
            "activity": {
              "ref": "#log",
              "input": {
                "message": "=$flow.in",
                "addDetails": "false"
              }
            }
          }
        ],
        "links": []
      }
    }
  ]
}
